/This q script is used to calculate the vwap from transaction records

/read data generated by python to kdb
transac_record:("PSFI";",") 0:`data.csv

/convert to table
transac_table:flip `time`ticker`price`size!transac_record

/calculate the date from date time
transac_table: update date: `date$transac_table`time from transac_table

/calculate the daily vwap
vwap:select vwap:(sum price*size)%(sum size) by date,ticker from transac_table

/out put the result
save `:vwap.csv
